app:
  name: Application-Local
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajadithya2348430/config-server
  app:
    name: Application

server:
  port: 8888