application:
  name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajadithya2348430/config-server
  profiles:
    active: dev

server:
  port: 8888
